@echo off
echo Killing any processes using port 3000...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3000') do taskkill /f /pid %%a 2>NUL
echo Starting development server on port 3000...
npm run dev
